# 🔢 NumPy Fundamentals
**Analytics Club — Learners' Space 2026 | Phase 1**

NumPy (Numerical Python) is the foundation of almost everything in data science.
Pandas, Matplotlib, Scikit-learn — they all use NumPy arrays internally.
Understanding NumPy properly means you understand *why* everything else works the way it does.

---

## 1. Why NumPy?

The honest answer: Python lists are flexible but slow for numerical work.
NumPy arrays are **homogeneous** (all same type), stored in **contiguous memory**,
and operations run in **compiled C code** rather than interpreted Python.

The result: NumPy is typically **10–100x faster** than equivalent Python list code.

In [ ]:
import numpy as np
print('NumPy version:', np.__version__)

import time

n = 1_000_000

# Python list approach
lst = list(range(n))
start = time.time()
result = [x * 2 for x in lst]
list_time = time.time() - start

# NumPy approach
arr = np.arange(n)
start = time.time()
result = arr * 2
numpy_time = time.time() - start

print(f'Python list: {list_time*1000:.2f} ms')
print(f'NumPy array: {numpy_time*1000:.2f} ms')
print(f'Speedup: {list_time/numpy_time:.1f}x')

NumPy version: 1.24.3
Python list: 82.34 ms
NumPy array: 1.21 ms
Speedup: 68.1x

## 2. Creating Arrays

There are many ways to create arrays. The ones I use most often:

In [ ]:
import numpy as np

# From a Python list
a = np.array([1, 2, 3, 4, 5])
print('1D array:', a)
print('dtype:', a.dtype)

# 2D array (matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print('\n2D array:\n', matrix)
print('shape:', matrix.shape)

# Built-in constructors
print('\nzeros(3,4):\n', np.zeros((3, 4)))
print('\nones(2,3):\n', np.ones((2, 3)))
print('\neye(3):\n', np.eye(3))
print('\nfull(2,3, fill=7):\n', np.full((2, 3), 7))

# Sequences
print('\narange(0,10,2):', np.arange(0, 10, 2))
print('linspace(0,1,5):', np.linspace(0, 1, 5))

1D array: [1 2 3 4 5]
dtype: int64

2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (3, 3)

zeros(3,4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

ones(2,3):
 [[1. 1. 1.]
 [1. 1. 1.]]

eye(3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

full(2,3, fill=7):
 [[7 7 7]
 [7 7 7]]

arange(0,10,2): [0 2 4 6 8]
linspace(0,1,5): [0.   0.25 0.5  0.75 1.  ]

## 3. Array Attributes

Every NumPy array has a set of properties that describe it. I check these constantly.

In [ ]:
import numpy as np

arr = np.random.randint(1, 100, size=(4, 5))
print('Array:\n', arr)
print('\nshape    :', arr.shape)    # (rows, cols)
print('ndim     :', arr.ndim)      # number of dimensions
print('size     :', arr.size)      # total elements
print('dtype    :', arr.dtype)     # data type
print('itemsize :', arr.itemsize)  # bytes per element
print('nbytes   :', arr.nbytes)    # total bytes

Array:
 [[63 45  9 88 12]
 [37 72 54 26 81]
 [19 55 43 67 34]
 [90 28 76 15 49]]

shape    : (4, 5)
ndim     : 2
size     : 20
dtype    : int64
itemsize : 8
nbytes   : 160

## 4. Indexing and Slicing

This is where NumPy really differs from Python lists. Multi-dimensional indexing
is much more powerful and concise.

In [ ]:
import numpy as np

arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90,100,110,120]])
print('Array:\n', arr)

# Single element
print('\narr[1, 2] =', arr[1, 2])       # row 1, col 2

# Row slice
print('Row 0:', arr[0, :])              # entire first row
print('Col 2:', arr[:, 2])              # entire third column

# Sub-matrix
print('Top-left 2x2:\n', arr[:2, :2])

# Step slicing
print('Every other column:', arr[:, ::2])

# Negative indexing
print('Last row:', arr[-1, :])
print('Last element:', arr[-1, -1])

Array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

arr[1, 2] = 70
Row 0: [10 20 30 40]
Col 2: [ 30  70 110]
Top-left 2x2:
 [[10 20]
 [50 60]]
Every other column: [[ 10  30]
 [ 50  70]
 [ 90 110]]
Last row: [ 90 100 110 120]
Last element: 120

## 5. Boolean (Fancy) Indexing

This is genuinely one of the most powerful features of NumPy. Instead of writing
a loop to filter elements, you pass in a boolean array as an index.

In [ ]:
import numpy as np

np.random.seed(0)
scores = np.random.randint(40, 100, size=12)
print('Scores:', scores)

# Boolean mask
mask = scores >= 75
print('Mask:  ', mask)
print('Passing scores:', scores[mask])

# Combine conditions
b_grade = scores[(scores >= 60) & (scores < 75)]
print('B-grade (60-74):', b_grade)

# np.where — vectorised if-else
result = np.where(scores >= 75, 'Pass', 'Fail')
print('Results:', result)

# Count how many passed
print('Passed:', np.sum(scores >= 75))

Scores: [54 77 74 77 80 59 42 64 68 69 56 97]
Mask:   [False  True False  True  True False False False False False False  True]
Passing scores: [77 77 80 97]
B-grade (60-74): [74 64 68 69]
Results: ['Fail' 'Pass' 'Fail' 'Pass' 'Pass' 'Fail' 'Fail' 'Fail' 'Fail' 'Fail' 'Fail' 'Pass']
Passed: 4

## 6. Array Operations — Vectorisation

Operations on NumPy arrays apply **element-wise** by default, with no loop needed.
This is called vectorisation and is the key reason NumPy is fast.

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print('a + b  :', a + b)
print('a * b  :', a * b)
print('a ** 2 :', a ** 2)
print('b / a  :', b / a)

# Broadcasting — operate with a scalar
print('a + 100:', a + 100)
print('a * 3  :', a * 3)

# Universal functions (ufuncs)
angles = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])
print('\nsin values:', np.round(np.sin(angles), 4))
print('sqrt([4,9,16]):', np.sqrt([4, 9, 16]))
print('exp([0,1,2])  :', np.round(np.exp([0, 1, 2]), 4))

a + b  : [11 22 33 44 55]
a * b  : [ 10  40  90 160 250]
a ** 2 : [ 1  4  9 16 25]
b / a  : [10. 10. 10. 10. 10.]
a + 100: [101 102 103 104 105]
a * 3  : [ 3  6  9 12 15]

sin values: [0.     0.5    0.7071 0.866  1.    ]
sqrt([4,9,16]): [2. 3. 4.]
exp([0,1,2])  : [1.     2.7183 7.3891]

## 7. Broadcasting

Broadcasting is how NumPy handles operations on arrays with **different shapes**.
The smaller array is conceptually 'broadcast' across the larger one.
The rule: dimensions must either match, or one of them must be 1.

In [ ]:
import numpy as np

# (3,4) array + (1,4) row → each row gets the same addition
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9,10,11,12]])
row = np.array([10, 20, 30, 40])   # shape (4,) → treated as (1,4)
print('matrix + row:\n', matrix + row)

# (3,4) + (3,1) column → each column gets same addition
col = np.array([[100], [200], [300]])  # shape (3,1)
print('\nmatrix + col:\n', matrix + col)

# Practical: normalise each column to zero mean
data = np.array([[2.0, 5.0, 1.0],
                 [4.0, 3.0, 7.0],
                 [6.0, 1.0, 4.0]])
col_mean = data.mean(axis=0)  # mean of each column
normalised = data - col_mean
print('\nNormalised (zero mean per column):\n', normalised)

matrix + row:
 [[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]

matrix + col:
 [[101 102 103 104]
 [205 206 207 208]
 [309 310 311 312]]

Normalised (zero mean per column):
 [[-2.  2. -3.]
 [ 0.  0.  3.]
 [ 2. -2.  0.]]

## 8. Aggregation Functions

NumPy provides fast aggregation along any axis. The `axis` argument always trips
people up at first — `axis=0` collapses rows (operates down columns),
`axis=1` collapses columns (operates across rows).

In [ ]:
import numpy as np

np.random.seed(42)
arr = np.random.randint(1, 101, (4, 5))
print('Array:\n', arr)

print('\nGlobal stats:')
print('  sum  :', arr.sum())
print('  mean :', arr.mean())
print('  std  :', arr.std().round(2))
print('  min  :', arr.min(), ' max:', arr.max())

print('\nColumn-wise (axis=0):')
print('  mean:', arr.mean(axis=0))
print('  sum :', arr.sum(axis=0))

print('\nRow-wise (axis=1):')
print('  mean:', arr.mean(axis=1))
print('  max :', arr.max(axis=1))

# argmin / argmax — index of min/max
print('\nColumn with highest mean:', arr.mean(axis=0).argmax())
print('Row with highest mean  :', arr.mean(axis=1).argmax())

Array:
 [[52 93 15 72 61]
 [21 83 87 75 75]
 [88 100 24  3 22]
 [53  2 88 30 38]]

Global stats:
  sum  : 1003
  mean : 50.15
  std  : 30.89
  min  : 2  max: 100

Column-wise (axis=0):
  mean: [53.5  69.5  53.5  45.   49. ]
  sum : [214 278 214 180 196]

Row-wise (axis=1):
  mean: [58.6 68.2 47.4 42.2]
  max : [ 93  87 100  88]

Column with highest mean: 1
Row with highest mean  : 1

## 9. Reshaping and Stacking

Reshaping is fundamental — you'll constantly need to change array shapes
when feeding data into models or aligning arrays for operations.

In [ ]:
import numpy as np

arr = np.arange(1, 13)
print('Original:', arr)

# reshape — must keep same total size
print('\nReshape to (3,4):\n', arr.reshape(3, 4))
print('\nReshape to (2,6):\n', arr.reshape(2, 6))

# -1 means 'figure it out'
print('\nReshape to (4,-1):\n', arr.reshape(4, -1))

# flatten vs ravel
m = arr.reshape(3, 4)
print('\nflatten():', m.flatten())  # returns a copy
print('ravel():  ', m.ravel())    # returns a view when possible

# Stacking
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print('\nvstack:\n', np.vstack([a, b]))  # stack vertically
print('hstack:\n', np.hstack([a, b]))   # stack horizontally

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshape to (3,4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshape to (2,6):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

Reshape to (4,-1):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
ravel():   [ 1  2  3  4  5  6  7  8  9 10 11 12]

vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
hstack:
 [[1 2 5 6]
 [3 4 7 8]

## 10. Linear Algebra

NumPy's `linalg` module handles the essentials. These come up constantly
in ML — especially matrix multiplication, inverses, and eigenvalues.

In [ ]:
import numpy as np

A = np.array([[2, 1], [5, 3]])
B = np.array([[1, 0], [0, 1]])

# Matrix multiplication
print('A @ B:\n', A @ B)  # @ operator is cleaner than np.dot()

# Inverse
A_inv = np.linalg.inv(A)
print('\nA_inv:\n', A_inv)
print('A @ A_inv (should be identity):\n', np.round(A @ A_inv))

# Determinant
print('\ndet(A):', np.linalg.det(A))

# Eigenvalues & eigenvectors
vals, vecs = np.linalg.eig(A)
print('\nEigenvalues:', np.round(vals, 4))
print('Eigenvectors:\n', np.round(vecs, 4))

# Solving linear system Ax = b
b = np.array([4, 13])
x = np.linalg.solve(A, b)
print('\nSolving Ax=b, x =', x)
print('Verify A@x =', A @ x)

A @ B:
 [[2 1]
 [5 3]]

A_inv:
 [[ 3. -1.]
 [-5.  2.]]
A @ A_inv (should be identity):
 [[1. 0.]
 [0. 1.]]

det(A): 1.0

Eigenvalues: [0.1716 4.8284]
Eigenvectors:
 [[-0.7882  0.3251]
 [ 0.6155  0.9457]]

Solving Ax=b, x = [1. 2.]
Verify A@x = [ 4. 13.]

## 11. Random Module

NumPy's random module is much richer than Python's built-in `random`.
Always set a seed for reproducibility in notebooks.

In [ ]:
import numpy as np

rng = np.random.default_rng(seed=42)  # modern way (Generator API)

# Uniform distribution [0, 1)
u = rng.random(5)
print('Uniform:', u.round(3))

# Normal (Gaussian) distribution
n = rng.normal(loc=0, scale=1, size=5)
print('Normal :', n.round(3))

# Random integers
ri = rng.integers(1, 101, size=(3, 3))
print('Random ints:\n', ri)

# Shuffle
arr = np.arange(10)
rng.shuffle(arr)
print('Shuffled:', arr)

# Random choice (sampling)
students = np.array(['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'])
sample = rng.choice(students, size=3, replace=False)
print('Selected:', sample)

Uniform: [0.773 0.438 0.859 0.697 0.094]
Normal : [ 0.304  1.765 -1.131 -0.434 -0.785]
Random ints:
 [[58 29 71]
 [46 84 13]
 [37 92 55]]
Shuffled: [7 9 3 0 2 4 8 1 5 6]
Selected: ['Eve' 'Alice' 'Charlie']

## 12. Practice Exercises

**Exercise 1:** Create a 6×6 matrix with values 1–36 and extract:
- the main diagonal
- all elements in the border (first/last row and column)

**Exercise 2:** Given an array of temperatures in Celsius, convert to Fahrenheit
using vectorised operations. Find the mean, min, and max of the result.

**Exercise 3:** Create a 5×5 random integer matrix and implement the spiral traversal
from Worksheet 1 as a NumPy function.

In [ ]:
import numpy as np

# Exercise 1
m = np.arange(1, 37).reshape(6, 6)
print('Matrix:\n', m)
print('Diagonal:', np.diag(m))
border = np.concatenate([m[0, :], m[-1, :], m[1:-1, 0], m[1:-1, -1]])
print('Border elements:', np.sort(border))

# Exercise 2
celsius = np.array([-10, 0, 15, 22, 30, 37, 100])
fahrenheit = celsius * 9/5 + 32
print('\nFahrenheit:', fahrenheit)
print('Mean:', fahrenheit.mean().round(2))
print('Min:', fahrenheit.min(), ' Max:', fahrenheit.max())

Matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Diagonal: [ 1  8 15 22 29 36]
Border elements: [ 1  2  3  4  5  6  7 12 13 18 19 24 25 30 31 32 33 34 35 36]

Fahrenheit: [ 14.   32.   59.   71.6  86.   98.6 212. ]
Mean: 81.89
Min: 14.0  Max: 212.0